name: Extract Translations
on: 
  push:
    branches:
      - localization
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  
jobs:
  extract_translations:
    name: Extract Translations
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Setup Google Api credentials
      run: | 
        echo "${{secrets.GOOGLE_API_KEY}}" | base64 -d > /tmp/account.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/account.json" >> $GITHUB_ENV
    - name: Extract translations using PoExtractor
      run: |
        dotnet tool install --global PoExtractor.OrchardCore --version 0.4.0-rc1-13272
        mkdir ${{github.workspace}}/translation_workdir
        extractpo-oc ${{github.workspace}}/src ${{github.workspace}}/translation_workdir/extract
    - name: Auto translate missing translation strings
      run: |
        cd ./translation_script
        npm install
        node po-gtranslator.js --project_id=oc-translation --po_source="${{github.workspace}}/translation_workdir/extract" --po_dest="${{github.workspace}}/src/StatCan.OrchardCore.Cms.Web/Localization/fr" --lang=fr
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Update translations
        signoff: false
        base: localization
        branch: update-localizations
        delete-branch: true
        title: '[Localization] Update translations'
        body: |
          - Auto-generated by the [Extract Translation][https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID] action
        labels: |
          localization
        assignees: jptissot

    - name: Check pull request output
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
    - uses: actions/upload-artifact@v2
      with:
        name: Extracted translation files
        path: |
          ${{github.workspace}}/translation_workdir/
        retention-days: 1
